/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
});
export const SharedBuild = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'previewData' : IDL.Text,
  'comments' : IDL.Vec(Comment),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Build = IDL.Record({
  'id' : IDL.Text,
  'partsJson' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const GuideProgress = IDL.Record({
  'guideId' : IDL.Text,
  'user' : IDL.Principal,
  'completed' : IDL.Bool,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeGuide' : IDL.Func([IDL.Text], [], []),
  'deleteBuild' : IDL.Func([IDL.Text], [], []),
  'getAllSharedBuilds' : IDL.Func([], [IDL.Vec(SharedBuild)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([], [IDL.Vec(GuideProgress)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeBuild' : IDL.Func([IDL.Text], [], []),
  'saveBuild' : IDL.Func([Build], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shareBuild' : IDL.Func([SharedBuild], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
  });
  const SharedBuild = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'previewData' : IDL.Text,
    'comments' : IDL.Vec(Comment),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Build = IDL.Record({
    'id' : IDL.Text,
    'partsJson' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const GuideProgress = IDL.Record({
    'guideId' : IDL.Text,
    'user' : IDL.Principal,
    'completed' : IDL.Bool,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeGuide' : IDL.Func([IDL.Text], [], []),
    'deleteBuild' : IDL.Func([IDL.Text], [], []),
    'getAllSharedBuilds' : IDL.Func([], [IDL.Vec(SharedBuild)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserBuilds' : IDL.Func([], [IDL.Vec(Build)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([], [IDL.Vec(GuideProgress)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeBuild' : IDL.Func([IDL.Text], [], []),
    'saveBuild' : IDL.Func([Build], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shareBuild' : IDL.Func([SharedBuild], [], []),
  });
};

export const init = ({ IDL }) => { return []; };