/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Build {
  'id' : string,
  'partsJson' : string,
  'name' : string,
  'description' : string,
  'timestamp' : Time,
}
export interface Comment {
  'content' : string,
  'user' : Principal,
  'timestamp' : Time,
}
export interface GuideProgress {
  'guideId' : string,
  'user' : Principal,
  'completed' : boolean,
  'timestamp' : Time,
}
export interface SharedBuild {
  'id' : string,
  'title' : string,
  'likeCount' : bigint,
  'description' : string,
  'author' : Principal,
  'timestamp' : Time,
  'previewData' : string,
  'comments' : Array<Comment>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeGuide' : ActorMethod<[string], undefined>,
  'deleteBuild' : ActorMethod<[string], undefined>,
  'getAllSharedBuilds' : ActorMethod<[], Array<SharedBuild>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserBuilds' : ActorMethod<[], Array<Build>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[], Array<GuideProgress>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeBuild' : ActorMethod<[string], undefined>,
  'saveBuild' : ActorMethod<[Build], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shareBuild' : ActorMethod<[SharedBuild], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];